apiVersion: v1
kind: Service
metadata:
    name: "env1aksvpc3eu2iyyh4i-dbd8"
    labels:
        app: "env1aksvpc3eu2iyyh4i-dbd8"
spec:
    type: LoadBalancer
    ports:
    - port: 2222
      targetPort: 2222
      protocol: TCP
      name: http
    selector:
        app: "env1aksvpc3eu2iyyh4i-dbd8"